// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1jnA4f--RJQaeS16v9gNyLly_IVc3mgY',
    appId: '1:1007356461142:web:9c313be73dd3de355cbbf7',
    messagingSenderId: '1007356461142',
    projectId: 'fruits-detector-f6218',
    authDomain: 'fruits-detector-f6218.firebaseapp.com',
    storageBucket: 'fruits-detector-f6218.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBl83lgq81jWQw2SSLRUuKFFa-Ww9O94G4',
    appId: '1:1007356461142:android:67790ca990dbdde05cbbf7',
    messagingSenderId: '1007356461142',
    projectId: 'fruits-detector-f6218',
    storageBucket: 'fruits-detector-f6218.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOYUeTV5leHmALWP0xQG7PQRcz4TAXFzk',
    appId: '1:1007356461142:ios:51c845544464ae735cbbf7',
    messagingSenderId: '1007356461142',
    projectId: 'fruits-detector-f6218',
    storageBucket: 'fruits-detector-f6218.firebasestorage.app',
    iosBundleId: 'com.example.pawty',
  );
}
